apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "jellyfin"
  namespace: argocd
spec:
  spec:
    syncPolicy:
      automated:
        prune: true
  project: "mediaserver"
  source:
    repoURL: "https://github.com/enrico-laboratory/homelab"
    targetRevision: HEAD
    path: "k8s/mediaserver/jellyfin"
  destination:
    server: https://kubernetes.default.svc
    namespace: "mediaserver"
  syncPolicy:
    automated:
      selfHeal: true