apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "radarr"
  namespace: argocd
spec:
  project: "mediaserver"
  source:
    repoURL: "https://github.com/enrico-laboratory/homelab"
    targetRevision: HEAD
    path: "k8s/mediaserver/radarr"
  destination:
    server: https://kubernetes.default.svc
    namespace: "mediaserver"
  syncPolicy:
    automated:
      selfHeal: true