apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "home-automation"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for the Home Automation
  sourceRepos:
    - 'https://github.com/enrico-laboratory/homelab'
  destinations:
    - namespace: "home-automation"
      server: https://kubernetes.default.svc
