apiVersion: v1
kind: Service
metadata:
  name: calibreweb-service
  namespace: mediaserver
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.231
spec:
  type: LoadBalancer
  selector:
    app: calibreweb
  ports:
    - port: 8083

