from notion_db.notion.music_projects import MusicProjectNotionModel
from notion_db.notion.choirs import ChoirNotionModel
from notion_db.notion.locations import LocationNotionModel
from notion_db.notion.tasks import TasksNotionModel