apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: mediaserver
  labels:
    app: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/linuxserver/jackett
          env:
            - name: LOG_LEVEL
              value: "info"

