apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed
  labels:
    app: librespeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librespeed
  template:
    metadata:
      labels:
        app: librespeed
    spec:
      containers:
        - name: librespeed
          image: ghcr.io/librespeed/speedtest:latest
          env:
            - name: MODE
              value: "standalone"
#            - name: PUID
#              value: "1000"
#            - name: PGID
#              value: "1000"
#            - name: TZ
#              value: "Europe/Amsterdam"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: librespeed-secrets
                  key: pass
          volumeMounts:
            - mountPath: /config
              name: config

      volumes:
        - name: config
          nfs:
            server: 192.168.100.61
            path: /mnt/fast-pool1/docker-configs/librespeed
