---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: librespeed-secrets
  namespace: tooling
spec:
  encryptedData:
    pass: AgBkj2YAqLlBTRsJR+j1lxzxjuav4oY59lNsqMZpIYpZVY9LWdzOGLYKYfwwL1YaJT9jobmni6AcIC6H41hY4SZg+4Qc1oAR4vicnffV00jJJgTW5zdDJ1Fm1OpU74Hexllarq947W94nAq55ZyTeU4MmBBcCgMKo2bOtYP3Y1jfnfMo1g7WZN4HQr+QQJKoXel3OGVGnVKSkBe2V3ffguRQITuhXCfKGIEuzrLoNgDB9rBU8SrMr5HWV/FHcibyG/9HfCsegUZxz0a/yCwWKGjV05xRYgb7iD8QM8I92GrbRdXeBSu2A+H8PDUDMSnWckYdq3WlRlhEIrgVIflACxPasQhLwqQNEyfjH+aGqDEGR7DntdahOWoqiwYJgmO7KV/VIK4HmN6o+Io14+kxFYBIr8MBxR6Az5O9HH9paxqRPN2TGQjq4kIoyi6toxoPsRUov20WS3XqqSFnYPgFNcMsciqtyghfBavqYWoDoJX1+ur5Lt3WfL+fyZPg08iMwgSZkOqRo5YdjsnTCcI4FDAfXkT+XtGEH5ngBDKVwQ/3EhzBoYw03bLCdbARgEuLiFpAFDqybQQi2D9DHNkaVY1jlz5PoFAmbKBH4g/Ya+sNxSywI1NND/3HRMfSX5Bk2fqSnDSA0ctMPDG4Bi6NjSBqDGOGhQ5A2S3hi2gwUrzCft6nHVluF69LLeR4fe21mARPramyGAJlAQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transmission
      name: librespeed-secrets
      namespace: tooling
    type: Opaque
