- name: create users
  hosts: pvenodes
  become: yes
  vars:
    users:
      terraform: "terraform"
      ansible: "ansible"


  tasks:

    - name: create user
      user:
        name: "{{ item }}"
        shell: "/bin/bash"
      loop:
        - "{{ users.terraform }}"
        - "{{ users.ansible }}"

    - name: create ssh key
      become: no
      shell:
        cmd: |
          ssh-keygen -q -N '' -f {{ item }}_rsa <<<n
      delegate_to: localhost
      ignore_errors: true
      changed_when: false
      loop:
        - "{{ users.terraform }}"
        - "{{ users.ansible }}"

    - name: send ssh pub key"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', item + '_rsa.pub') }}"
      loop:
        - "{{ users.terraform }}"
        - "{{ users.ansible }}"
