---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgCX+KnevQMlMvr3Uup/smCoF660YouReLjNmdknAMLC8SMsIaMD1wbMaaFFzEpJZ+6jBFjlWSWmKj3OwX0VtVJivzv1p88xI+rQjHAagmJ+Pyx+2QFV755HwhsO/L5Wp4lLfUGTLGaB0/vjM5S+aCVuFAo0A6Xs6FZwXSzV/rxdDkEETsFHEx3zfx6ZrakUk/F3kGtV/kKuFOojow8qpOXTPhs9XL4ZqWX81E38+KxtyV8jrIQxI3iSs9bFRH8lE0HhN4goQ5ydbkEsWx4rS/sPcvBHyN6zLBTpDmoSVCRbL/X6mMl3XQS3xKpWy1g6Wkige4MJwW8nWdmZWYtw1dpAalvuXdpCtvWdn04XiWrWwGhlOv9Wqun6U9QK8nfeYFrn7S7b4JZ9exJTz9ugTsSu5kVxf6OORdQOZsWcxYcedaa8sFzzPMW81qQbLGpRZQGaJYrZdy/47q9p8vsWhyL+FJ6g47nsMwaPOFVMHz3+ph5pEf05a8plubVPcY8k3G6zX4gqRIrCUP3h0ZZBMrny81G5yUK/kUPKgqKWEjCg9MOX8N5IwcUkJEgfGpR09Dlx1XD3SBMYejb1+m+JLHvdvS/MJWwxL8uMuqE92Si4LanmABbf+J+KtbCefUuCDHKnCKk1fsJXYrM4iJKNj3FLg2aDTDDADrFDGXrKqAM8r6bvAf/XLm14Fpeo89LVLXqPh+R1i3a4P3A=
    user: AgBg6vJmf/hMqh2I+0Oa1zS5GhM5ddmbGQLYMksE+hUX8JPHhwRC/o05kfH/2tHEufMtqPC2ddfLufxWn8Obc+H5VPlcChijKvX9c9/gj/1AMFfQU6vgFWGrsiR8y7dOjviiGwO1n8Y/kJNuEhwNGKxh4KskOzi+qBem9gkFhWDvZadg/EQLuhhbpxrW/SwAUsDSddUXWljXC30yiZUCaLV+zw/feayvBxcKOsxZinv3H98oJpL/pGhphb8flyGmjUB56AR+tYY+329To35BIu+SBAwLHBUI8XRkbpZvy69XJRvRRe96AzKqi3NjkzpzSe70zzk71nGGpuCpFOOHG/NiToFixJmfrb8OZWsq/1CO/KudgKteX8ziAjugWzrULl+UN2Bm7WZon85Sh0V7FfqSmQoX5cLcqtgOSnP4eRppeBMbP+ahWYXA0ndwodEPwJ2sU67bBtClVUC0Wzqq6zp0BdRLCQyIWvWXksEgQF5sF6SDxqVXXCngsxgS+ByvgRLE5uLAs5i570oxSMcbvy/pd3JTIUSNho/o5Rn8CZuaAnhJ04ATyeL6U4xmVgy9+DoSMk+KOcJzvEzPJnJUEF0NMA2KokxZkvo/Exh+QQdBCBuPUajEXWEkIm9WkMWW+CzNPbutAdoK6qdRu+3ZathUTrmdbjZBmEyCMdXNnK/yXib0Q3JvC27L8Tj7aaHIw2SW17YfuLSL
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transmission
      name: transmission-secrets
      namespace: mediaserver
    type: Opaque
