---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgAmwuhqIZF35VyQy/ggBbz5QFA35O2PjrltCCRD0qEc7GT90WS375R10LyYbI8CbFU1a611/jRhfOwUpYYUyJljo5PWjy2RZR7dxV5M9xFP+mJmxQHp0MksH6XY9//zVIBqYMS9jmU6HCzHFAq65WuIuL7UPc/xoYm6ntR9q/poQn1BQCOBPCBSWld+1jc3z26Rj9yHuv3pUp4e3MFB0clBNZRnHPC2Z9Nmsj25md8cgVowRHinuJvbjD3FjCcMPjhgokOTXBKcilcyuZovIqa7H+6rw3qV/RVLOeJbfuT+45XQ8TDZEdtEdZXS30L7hOtApHncR7GCfqnv7bF7j2tjVVOD9eB86FMIAXiXHdtyNy2G6QWUVgKkNcDuv0e5ZNvNbmsraP9UU29C7DyvBLdJYnjlf1QjWJgckLpwv+HxunX9KY1uzlgjsa4buwovAyyZ0mRm+LNBhLC28TOKV+nmGPkLaMQEn/v24mdJzOJTn/a1rGnVJahPyfYngTxtFt8kQt+eaGbUEaJ/VxlDUH8Fx8d6hIULiWnFzdjCIvHnWRt7gBgJAvTL4fcPSMmgINHEawzPOFaaxcCHPbcwrpmOvA8kzsWH6hcRjtW5Wuoyb//qQdELmI4UCyeQVrmuQar2wOXPrYUrOCeTVF8NntomdKO+/ALyC3+P67JI7OPsu3GLjyYqXFwaTaxNzs8i5GZFcitE/zNT0zQ=
    user: AgAc3D1DhMfpb2opTrYbE3kN9l3SBOnlzSOCQgZmzNvmsRFNUL8OOi2GOjhrSKdHKSCw2uCYSAzX6CqaCuSyWs8PKDcBKW60YOrkKb1Cll4XSjYa0k+wk25I3xX4uxqX3gzHKv5Fm5RmzvY9MqXJ25SLPAAoHTfi3VJpiWKbVqA2qsn2AlwoSOXeDu77kFgmvpWYfjvYxIlnvjg2+JDqtENwz40I5TQGbknpyDQmvvUArr1MheCF0f7iJXnZlneSdmHSXDzeDCYTxwzILKnyP1WUV5Jg+1GyH2JwkJ+eGCeSh0K1TPIX+D8WWUbKiuSBu+6797Md9HAgZXX60qf0TdJ/7WwkveOEMImruNuBX47YCJZmjAN/DNGkYikrn3hI/K/HZHJkmxj4qJlEENXjNEkQJOWKh10UQnv5xC2PoZK5fRmPH6nhF1UHRqMhzAmPPeateESD6r9AqayQhhId2zMRvVqVdN0ezwwIV9yPUQv+YH92nhHN1Wi1SJ0AhwEkuUQQbN2C+0MUXlS49hE3bLGvrF6z/WjSP5LSrlYtcVSbmoaxRikQpEp1Q5RBau4C3I0N3lW/B63YNw0wMdY6Sbq7cmzkwAB3ug3nBUOtmny982r3F58+32QSfRNeNHtbJv9uy9J1IKrjDf/Ev0sUCUNFtsO90ISVQ1SvS9BDJo7EmjbzvRsVes5fbDPIvDHY/PnrHD06wmro
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transmission
      name: transmission-secrets
      namespace: mediaserver
    type: Opaque
