---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgCZqvt2XgYbp5sB8TIFzkodCddVmeuUVd6WufnduuDccJq0cRHEqOinyZCWApii2JCu1drq35+ZFXupc5Z5OXjt1uYa/AME00RhNjcC5RYQs6uMaji7P3ULjYnpirRQlF0wc8pjnO86NheKAzFIdf261omfB+hWYtJaqFPF/i1mbmZITSSjuqSFZwQIWubOIf+1+5OlfV6uYBRo3b8QC90572JHVOtdQGgN3Y+MDq6Yu56wIcZCHZZNnZCL2c8wx5OAX3l2CqQdsoekXrbEubGkMpA1sng6lVu6xGkdDGzp3nmoUg8CZa/pKRAJjNsnRvx8DXXcRM/D0+Kia2x7wWwPu4eM1N042UA4v0BjhpLHWlSPEHhq3F1/2m/ubSqPdDkhsdWjAJ/760KXuDmL9E9Wrxay+mg1ABWUvk/fVxE7uGzewP+7Koy82DguqAyFcblAB/47wYZzV/Np0RxZmUMXuKM5XsDYcS3b7C6ISymsFpUBIzXtyaEwSABc2QZDMZPXf2irPbgwtFwOx59CPCcg40kiQyfpjeGlwh/v3KKBMZm+ZqIf2hACp9NybuIvAA+k8MZ/DddoV+HhJ5doqCDOKpwwEzXQYgQ+nEbl4cm3JmZJQJLpRgIICYtHRhDfVabvS0BtxQobYW5O56oPtwfUnUNiQtBfuS8JEG1yTvTCYjA/BaApxG/YYuskwOnzrRfBVzaIb/F1zjM=
    user: AgAeAtN2yFxpOW+AhvHLbufTH4KbWf1eGqqlPViYxudEE16wYUB28rgUDPgAGxZsWQF7YUAxjhtdwtA4Vd9bhtOiif+9u7iXwJSE8Ww1PYPoImXaE3JWKroOBtBwkjr46MJkpqs7mnkkp9WazhBsiM5CvuG6G1Inyk3dLJAenL4d7uk8UDy5Wco6mQZuDarp3UwwzXcjDWGptm5n4CfbMVSqKy2mtKe6gqr7swnJYlj0ry6esLiWb3AgISLfYrlsl468yN/aPEnSPS8oBfDf3jDF99/o87HV4vt0gkvUffLUjfOsdpCJSB1qQ2qm4ekhF3j7zCfaHk59ukZ/1jWTFMmSRs2tbs907De0ssnzPVGDJm7AV7o1EW3fLC+4urbPIRJkvdH3vjOzzJD3Vjn71VFG6Q44jLh3mNhGNpWwcVVWOKhNc61D77i4x8WhunAjo9rY2u0ni8zWiJOhlrhd4DcqlZpSqe/YNlStWKtfEDSND6ha1rHh7P1e2ChHZF2yNjD3FS4Augg40SVZBVuPg2bs2Pj/H+bxHuvVudrEHkMkHN3KTAsOMNGE6p0KVFKByobbMy8n4pyzS/j1t6uadX3DvOajIKpx4dMyDrT3qZGap3hpJ56ywYDfFuNrj9NepUAvQFALFioBI6ZgfTRXEV4qmyvokYfyEOil5PWlONT9lZzPXsGQYLWv7a4D+05BvtIadPSK3zTs
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transmission
      name: transmission-secrets
      namespace: mediaserver
    type: Opaque
