---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgDlcHqJn6X9XRSHAmptP5/Byhuf3EW2eRZ/1BLZcMDR1H8IZVJjW7RbJNTC/BTP5jtddu3Q8GoiqrCPbP+W9BSguDd1vcp2E7/nOQT/Zg9jfkTOoFdgPLh3xrkzCNnDR2PSYpXpXAlI+c75Su3frU8sdojy8IIHHVoxs3MJioF+AJUFp6UJfjXJiRqS/L5ZLIkzMYPZn2Xem3N4ZePpnntm0hp/LrQbGVSHApVzm6x1Q3w657NvCc+5ED7Viv9flcYSggwU9LSwtnoKiQRz2VWTmRFCP4E7/LTwHlXbjy6BokATzHen62s0U3PHb56WZN0m5k5IuSOpvh//1tOKuxZkD20nEVuYWq391jWHb5zisKdDHZFfYJkxLMQXcj5OJAO8A90mdsykgquuwVPITEoIvwPWzvsKe6+Th+DZgIsUSc+atOAnJ1mCBX5+oIk06Kp0SyTjo3T6Xp4jiutXyuWE/LCDt8zpgVwERRYVwOKID+8mrtAMUNpX+eraPaZ+mD+9OYE3KB/zUK2wVsT15ERsaqGMjKARtBZvq+p9HgfwotCgT86MpklJzjNcF8+1RGEERX9eBf4AFbLiyPyqhpW4qCeEskwpGgP1QiZD1kKloeGevBeZ8yFaY+Da3Hs7XIZZNPc6yNljU+523acUiq/S6WA+9k2nGNcJtoNznnl7aQjnXvQD8yCWLyTeL+FV454xVv8s4L88XAo=
    user: AgBoQw62YSPGP+kRe3OJsmRmzbOJBaaDFShMr0fVeozzgiCqbg0PycogUcvk78WF9xZTZBve6ufF/xBBmGNPMWw6t/6khDRpv8gZ+7rtvY7LRgmuaruJbHp9Fkuym5UnqBE8OSmd2NZE52BkBRdN9x0of/T6u7bWtCcPJclf9AyhxFyTTZpytV97/RKFARgh7viAcVKbULMGfXSoF57EuU6iuosreLNZDcA0hIv4MIN7LkJdEfVq0lVDJF1RJXbqjP0Ch949Dvw3RvJjzLP6/G7IZvOhPK0QkdrTfmENB4BAHEeax1qj7POe8EQxNgAdK5sXlBGe9yjFeRJPSoug3WBIZ7EyxYvlRZWD+i+r5k+TpvK8qw2pyHIqPOl+nMkGKRmar/Map1bMODRjWxQ9KcgY4ep7IxYN7rm7go1dXXEkIo05V4ZYzwZwM+m0AoCVoApRNDOXD+Emaz6WZYZWf9F3pJ1MJV50uDlLx3I7Q7uChw0RTnM82hjkZ2wIbdCY8769FrXxo5lJ/OmTkbOBEDR/YNplP9DOuD5ErhmK0P08hRukbdjWlwcSZDtfllRENOCdJLnverZUCDtBSFF++kNEEg9he5xAyCm62xxH837m4t37c4Mfx15TkvLVfH8G39Q+iDBPBXSuvTwbO5FT8dUGKy0YOMe8aW6kpieyNMiZxLR0TmAzySUsRL696aRICCSih3rdL4pR
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transmission
      name: transmission-secrets
      namespace: mediaserver
    type: Opaque
