---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secrets
  namespace: mediaserver
spec:
  encryptedData:
    pass: AgBsStDXAxSoPO1PIxeRLa8tqZqH3iYcJMP/3g5z9OyCSp5zKlQfEtDNzrZqeocUSvkAxnrq/pbYUTWJCjiIYH30Xju5HvMCjuQcFfl05IqpSdS6Vx6435J+EwUgLnekSk8xKUFgJIBY1whpWBs89j6QdWnb4eJ95wd8i48K7joO6KCM8oKqaW3RJ/e2mtc8EbXFfKXHyvIBAYQyXj6CbOchA/9d8mcSe60mdZJ0mcS7HNJdHjmImt5oIBu19tnk4yQ+3MFAanRLwyVsmB3P2uCoZ4fMEPloSAYJJwgK70P7ucYCBQlZLZBDcq30wAh24ofqj1wKkzhCC9KFPbfIK9dM9rkbvf+/U1LbFsy/aHgPknuoP9TzFjrLNFfOWGw1nekiNbw0mgkH3ol9XlEIbkXPqi+sLPNK2RsEzQGidO678uAHrhXFFwRtmfAEztH2Cqtnjc9Ldou/mpsrGCLK5Et0m9KQt6P2CQjHQkM5JYR7nsmfJf9qhVE8+F3lxcflVBNxQCIiG8dPyI9Qhhe5Q8POHnJnU4+YM93ZfFEkQu/jdKQv1WWM4lgBaO0wXi7m/nbPF0ailI54GIDDPq4mC/jramJzpW2ZGRokxisQmP6CRpCC+EPgNjFdUAVMGKf0cWKYqGzZwyP+DbPfDM5TIvrqVAep3ons+/pm+Vs2cc2wfA+J3wcCto1mRzHOgXocZVbnbDt9RvSvDho=
    user: AgAxZnHHaxqmodL/fZcOX90Y+FLKJBGArfF/K+unHoXcZC3KsCi+iMDFLrCRKfuchnO2PrOENKme7mNFdssLSfdZHSjCdK+qo3hZI+5ubpSC9VZ3vwU55dZ/R5YRo45D7wtOWnbS0Gv4JcA/XRnIFdpethF6xNlJRp468Zpc7SOEotuNtaWrTFyK4I9qVDwcl3bGhRyILhcfcSa3nxd1RbtYXQ40fMgm/vHGT97RP/4zCAZ20pL/J9xqCxUsA+XPcFcnI5u44KmV0uWc8xFTRllcqIqfTu4SrQPHTyFwlE1Trpf+BPcPYOyZExT7/oM3V75bc46MCwQIVDW/7uzD9F9lx2ZtO7kYrlNDTw3Rtgo09ITz+QZoa6BkY/9oqQ7lTtGPsYK2S8IMu+LyL7k97vDiui+pRnFj2GcccumrQvxigB0MMojz8M365y1vMQKm2ZD+aakqMqdWpY41rnTxTgqwzqggE5UVeQSvjs7++gLgITZ4OKPiSsXcGscdeBDQcUTIbpcj2wbETc0RObH9EPO/2jLFnGyu3TyirxdWSMrAI8U7lt5aLoGoeu611bTvNuwjCHlxHK/W2bwbHQvoCDhT5bZIsSrNbWwbSIx32rJUM7aFVozjzgsE2Dr4ZOdM3mIyBDVPLb3LG+IDDQV/1I3RAX8tuWDZzevs2l3muIrHJxee29CS4maUh+EriC6h8OY3/35iJJ+C
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transmission
      name: transmission-secrets
      namespace: mediaserver
    type: Opaque
