apiVersion: v1
kind: Service
metadata:
  name: transmission-service
  namespace: mediaserver
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.237
spec:
  selector:
    app: transmission
  ports:
    - port: 9091
