
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-clusterrole-kubeapiserver
rules:
  - apiGroups: [""]
    resources:
      - nodes/metrics
      - nodes/proxy
      - nodes/stats
      - nodes/log
      - nodes/spec
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy-role-binding-kubernetes-master
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proxy-clusterrole-kubeapiserver
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: kube-apiserver
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cattle
  namespace: cattle-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cattle-admin-binding
  namespace: cattle-system
  labels:
    cattle.io/creator: "norman"
subjects:
  - kind: ServiceAccount
    name: cattle
    namespace: cattle-system
roleRef:
  kind: ClusterRole
  name: cattle-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: cattle-credentials-ac6dabc
  namespace: cattle-system
type: Opaque
data:
  url: "aHR0cHM6Ly8xOTIuMTY4LjEwMC43OA=="
  token: "amQ4OWRxcGc1Mjd4bGM0OXR4dGZ3Z3RkNGxoem1mNHN2ejZmd2puOXY1Z2dxc3Zjd3EyOHY3"
  namespace: ""

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cattle-admin
  labels:
    cattle.io/creator: "norman"
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cattle-cluster-agent
  namespace: cattle-system
  annotations:
    management.cattle.io/scale-available: "2"
spec:
  selector:
    matchLabels:
      app: cattle-cluster-agent
  template:
    metadata:
      labels:
        app: cattle-cluster-agent
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/controlplane
                    operator: In
                    values:
                      - "true"
              weight: 100
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: In
                    values:
                      - "true"
              weight: 100
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: In
                    values:
                      - "true"
              weight: 100
            - preference:
                matchExpressions:
                  - key: cattle.io/cluster-agent
                    operator: In
                    values:
                      - "true"
              weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: NotIn
                    values:
                      - windows
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - cattle-cluster-agent
                topologyKey: kubernetes.io/hostname
              weight: 100
      serviceAccountName: cattle
      tolerations:
        # No taints or no controlplane nodes found, added defaults
        - effect: NoSchedule
          key: node-role.kubernetes.io/controlplane
          value: "true"
        - effect: NoSchedule
          key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
        - effect: NoSchedule
          key: "node-role.kubernetes.io/master"
          operator: "Exists"
      containers:
        - name: cluster-register
          imagePullPolicy: IfNotPresent
          env:
            - name: CATTLE_IS_RKE
              value: "false"
            - name: CATTLE_SERVER
              value: "https://192.168.100.78"
            - name: CATTLE_CA_CHECKSUM
              value: "997bf33e551f40cf6b3e9b73df5cd10e777f8bd6b92c6cafb2a0da5bd6a1c73b"
            - name: CATTLE_CLUSTER
              value: "true"
            - name: CATTLE_K8S_MANAGED
              value: "true"
            - name: CATTLE_CLUSTER_REGISTRY
              value: ""
            - name: CATTLE_SERVER_VERSION
              value: v2.9.0
            - name: CATTLE_INSTALL_UUID
              value: eb70ed4c-ad50-4007-b2bc-5088cec6cea8
            - name: CATTLE_INGRESS_IP_DOMAIN
              value: sslip.io
            - name: STRICT_VERIFY
              value: "true"
          image: rancher/rancher-agent:v2.9.0
          volumeMounts:
            - name: cattle-credentials
              mountPath: /cattle-credentials
              readOnly: true
      volumes:
        - name: cattle-credentials
          secret:
            secretName: cattle-credentials-ac6dabc
            defaultMode: 320
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

---
apiVersion: v1
kind: Service
metadata:
  name: cattle-cluster-agent
  namespace: cattle-system
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 444
      protocol: TCP
      name: https-internal
  selector:
    app: cattle-cluster-agent