---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAmc9JasHvJMpQmDMpsVu1DxAAvown+RgQJmgVqf38as9S+rp70p1kzv4uR+zJWGMPDTA621bW5Fv6CQOd7d/HOMARwUeVui9rrHQ/85uMmLytrH2NXvdWRb3sGk6wChUq1yBIIzgBGRtZDjKbfhULYBJJcqz5LwdaLQsTazHf1367rk6T+eM3LdA4ifVgDKSIrwOMhOLJG5YNTmwWE7Fm71Cpjkj9v+EqQMNWpfY3UMgQIregtvnJL9nh7UJUn/RGQNGkfcg+y8je6LFcPkbJ2fnNldoHZ1p9xwB40mq14E6huy6o87HPZ6BV187/si2/14jRd3ztldB87kT0/Zy4BJ8qddsL5rvYdX/pvF1nzBIwFnJ7+ZtRAShJeibHZkgko8ZPsLXSeUM3MigZVF7LrwfLpuhf5BiCiaraMCs7RCCxH5sfbxr/v8VC1s/PrPCBDskwofmDuKIlmTLoK5MTmzWEMfzQ2/ITx+zg+3HXjws9JCWUpvoW2RXDIa2Js7x1eZ5G1ayLNXf44ILq/1xtcPcXPh/E0FOfmYuAIfMNHC5+8W6wuXyK0DPX9LyqnpKTo8icW7576rKMxBAAUTURapFRL3pp+fVjVwHUUhr2mt8dT5ki5K+HwFfI+BVkJxTJ68TE9h46RE6OMVdEZRRbgeaby5llGL4ziJb7kaMajRS9J9+9IzvQhAmWFK7RFZ1lWrBKllMCp/n7mIZ09Sp3RP81sNCmmWN0IVZw8CAQd+iplc8GQ7nz8
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
