apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "cert-manager-issuer"
  namespace: argocd
spec:
  project: "tooling"
  source:
    repoURL: "https://github.com/enrico-laboratory/homelab"
    targetRevision: HEAD
    path: "k8s/tooling/cert-manager-issuer"
  destination:
    server: https://kubernetes.default.svc
    namespace: "cert-manager"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
