- name: download manifest
  get_url:
    url: "https://raw.githubusercontent.com/metallb/metallb/{{ version }}/config/manifests/metallb-native.yaml"
    dest: "~/metallb-native.yaml"
    mode: 0644
  changed_when: no

- name: apply metallb
  kubernetes.core.k8s:
    state: "{{ state }}"
    src: "~/metallb-native.yaml"
  register: metallb

- name: delete manifest
  file:
    dest: "~/metallb-native.yaml"
    state: absent
  changed_when: no

- name: Wait for deployment
  ansible.builtin.wait_for:
    timeout: 5
  when: metallb.changed

- name: assign IPs to metallb
  kubernetes.core.k8s:
    state: "{{ state }}"
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: first-pool
        namespace: metallb-system
      spec:
        addresses:
          - 192.168.100.200-192.168.100.254
  register: metallb

- name: Wait for assigning Ip pool
  ansible.builtin.wait_for:
    timeout: 5
  when: metallb.changed

- name: advertise pool
  kubernetes.core.k8s:
    state: "{{ state }}"
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: advertise
        namespace: metallb-system