- name: deploy vms
  proxmox_kvm:
    api_user: "{{ api_user }}"
    api_token_secret: "{{ lookup('file', 'api_token') }}"
    api_token_id: "{{ api_token_id_k3s }}"
    api_host: "{{ ansible_host }}"
    node: "{{ inventory_hostname }}"
    name: "{{ name }}"
    clone: "{{ template_name }}"
    newid: "{{ new_id }}"
    full: yes
    storage: "{{ storage_name | default('vmimages') }}"
    cores: "{{ cores | default('2') }}"
    memory: "{{ memory | default('2048' }}"
    format: qcow2
  register: present_state

- name: Wait for deployment
  ansible.builtin.wait_for:
    timeout: 10
  delegate_to: localhost
  when: present_state.changed

- name: update cloud-init values
  proxmox_kvm:
    api_user: "{{ api_user }}"
    api_token_secret: "{{ lookup('file', 'api_token') }}"
    api_token_id: "{{ api_token_id_k3s }}"
    api_host: "{{ ansible_host }}"
    node: "{{ inventory_hostname }}"
    name: "k3s-{{ item }}"
    update: yes
    # searchdomains: 'mydomain.internal'
    nameservers:
      - '8.8.8.8'
    net:
      net0: "{{ net0 | default('virtio,bridge=vmbr0') }}"
    ipconfig:
      ipconfig0: "ip={{ ip_address }}/24"
