homelab:
  hosts:
    router:
      ansible_host: "192.168.100.1"

pvenodes:
  hosts:
    node01:
      ansible_host: "192.168.100.10"

k3s:
  hosts:
    k3s-1:
      ansible_host: "192.168.100.111"
    k3s-2:
      ansible_host: "192.168.100.112"
    k3s-3:
      ansible_host: "192.168.100.113"
    k3s-4:
      ansible_host: "192.168.100.114"
