apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-automation
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      tolerations:
        - key: "arm"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:latest
          env:
            - name: TZ
              value: Europe/Amsterdam
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /dev/ttyACM0
              name: sonoff
            - mountPath: /app/data
              name: data
      #            - mountPath: /config/configuration.yaml
      #              subPath: configuration.yaml
      #              name: configmap-file-india
      #            - mountPath: /config/automations.yaml
      #              subPath: automations.yaml
      #              name: configmap-file-india
      #            - mountPath: /dev/ttyUSB1
      #              name: zigbee
      securityContext:
        privileged: true
      hostNetwork: true
      volumes:
        - name: sonoff
          hostPath:
            path: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20240105134827-if00
        - name: data
          nfs:
            server: 192.168.100.61
            path: /mnt/fast-pool1/home-assistant/zigbee2mqtt/
#        - name: configmap-file-india
#          configMap:
#            name: ha-india-configmap
#        - name: zigbee
#          hostPath:
#            path: /dev/ttyACM0
