grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.enricoruggieri.com
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: trueNas
        static_configs:
          - targets: ['192.168.100.61:9100']
