- name: Configure network
  hosts: router
  become: yes
  tasks:

    - name: copy network config file
      copy:
        src: "40-network-config.yaml"
        dest: "/etc/netplan/"
        owner: root
        group: root
        mode: 0644
      register: copy

    - name: apply config
      shell:
        cmd: |
          netplan apply
      when: copy.changed

    - name: add port forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
        state: present
        reload: true
    - name: set rp filters
      ansible.posix.sysctl:
        name: net.ipv4.conf.default.rp_filter
        value: '1'
        sysctl_set: true
        state: present
        reload: true
    - name: set rp filters default
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '1'
        sysctl_set: true
        state: present
        reload: true

    - name: add NAT
      iptables:
        chain: POSTROUTING
        table: nat
        source: 192.168.100.0/24
        out_interface: ens16f1
        jump: SNAT
        to_source: 192.168.2.103

 #       iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o enp0s3 -j SNAT --to-source 80.0.0.1
