- name: Configure network
  hosts: router
  become: yes
  tasks:

    - name: copy network config file
      copy:
        src: "40-network-config.yaml"
        dest: "/etc/netplan/"
        owner: root
        group: root
        mode: 0644
      register: copy

    - name: apply config
      shell:
        cmd: |
          netplan apply
      when: copy.changed

    - name: add port forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
        state: present
        reload: true
    - name: set rp filters
      ansible.posix.sysctl:
        name: net.ipv4.conf.default.rp_filter
        value: '0'
        sysctl_set: true
        state: present
        reload: true
    - name: set rp filters default
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        sysctl_set: true
        state: present
        reload: true
