- name: install promethues node exporter
  hosts: pvenodes
  become: yes

  tasks:

  - name: install promethues node exporter
    include_role:
      name: install_node_exporter
    vars:
      node_exporter_version: "1.1.2"
      node_exporter_bin: /usr/local/bin/node_exporter
      node_exporter_user: node-exporter
      node_exporter_group: "{{ node_exporter_user }}"
      node_exporter_dir_conf: /etc/node_exporter