apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tooling
  name: tailscale-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-secret-reader-binding
  namespace: tooling
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale-secret-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tooling
