apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: tooling
  name: tailscale-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-secret-reader-binding
  namespace: tooling
roleRef: # points to the Role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale-secret-reader # name of Role
subjects: # points to the ServiceAccount
  - kind: ServiceAccount
    name: default # service account to bind to
    namespace: tooling # ns of service account
