---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-auth
  namespace: tooling
spec:
  encryptedData:
    TS_AUTHKEY: AgBtfjMbC8dc0nKxkPHD+K9lOGCZibnxySHScxFTBW255SdHWUyEGT2jzrJCoH/Pa180ML+hj0SoaXJRXN4XcTLTQGQBN9l0kUSGjedA8O2KuvPm5do5cycR1Cyu0ZMEP6mXgRgJZ3kwiTYcTlmuiFbq6t1ZDLVd5RhSH6IQq9tfpw/DT0dN+iYhoBdD+9no+NXRDzqQlc2+99fOJE/B3bj5+hgNspXu1ikQp5G9ureMDQkPzUJdP8T2B2JuFuh8ddiABTq7jewHBNLtjDjBftDGtX6jazET9kYPO3UlzOcjZNdLz8is2hEKcLoFYPhufOVleuH1HEgkQUPWVJBg1z09x+4U5okU+x3DwqI/lhuFd7OdCK/N3HcTGvo6gVsRytRxdFCuarFTxfnN/VEG0FYb0upoZk1zce9tzLiOox9HYuop0xASnh3PuN8l6m5ZEz7z/IKHPYqni/BMIYZ+iRTW/cxPRFyZ+TGOgjXDUAsRJCxQQ3EK69D9HJkLC/xrbLu27esD1DRXBr5K4fJVxz+fZPDWaUhqf/M3Uhl5C9kktXupXfxVKbNF9K1MXXZYeI+8G5dYgWSEXaAFffx7Bo3vf6qRMqRnt6M8zZ5ugTonTIRCv2ZTgPphQdLDVIzaF3iabwmSuufLJMaN05gbJ3X0vk9zphJRTH9bfa1HksI6/cGVECe84owX7EzbBs69jKN8JXx/VC5EqyVFY9Vy89Jype0B/EfrtZh0kIDCDyH9zyWdfpvUoGLSTHkPNRf0Tka2oeBNycAKMiMTXNca
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-auth
      namespace: tooling
    type: Opaque
