apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "metallb"
  namespace: argocd
spec:
  project: "tooling"
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.8
    helm:
      releaseName: metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: "tooling"
  syncPolicy:
    automated:
      selfHeal: true