- name: install ArgoCD
  hosts: k3s-1
  vars:
    sealed_secrets_state: "present"
    argocd_state: "present"
    argocd_ip_address: 192.168.100.201
  tasks:

    - name: Install sealed secret
      include_role:
        name: sealed_secrets
      vars:
        sealed_secrets_version: "v0.25.0"
        state: "{{ sealed_secrets_state }}"

    - name: Install argoCD
      include_role:
        name: argocd
      vars:
        state: "{{ argocd_state }}"
        ip_address: "{{ argocd_ip_address }}"

    - name: deploy repo secrets
      kubernetes.core.k8s:
        state: "present"
        namespace: "argocd"
        definition: "{{ lookup('file', 'repo_sealed_secrets.yaml' | from_yaml )}}"
