- name: MetalLB
  hosts:
    - k3s-1
  vars:
    metallb_state: "present"
    metallb_version: "v0.13.12"

  tasks:

    - name: Install metallb
      include_role:
        name: metallb
      vars:
        version: "{{ metallb_version }}"
        state: "{{ metallb_state }}"
