- name: MetalLB
  hosts:
    - k3s-1
  vars:
    state: "present"
  tasks:

    - name: download manifest
      get_url:
        url: "https://raw.githubusercontent.com/metallb/metallb/v0.13.12/config/manifests/metallb-native.yaml"
        dest: "~/metallb-native.yaml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
      when: state == "present"

    - name: apply metallb
      kubernetes.core.k8s:
        state: "{{ state }}"
        src: "~/metallb-native.yaml"
      register: metallb

    - name: Wait for deployment
      ansible.builtin.wait_for:
        timeout: 5
      when: metallb.changed


    - name: assign IPs to metallb
      kubernetes.core.k8s:
        state: "{{ state }}"
        definition:
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: first-pool
            namespace: metallb-system
          spec:
            addresses:
              - 192.168.100.220-192.168.100.254

    - name: advertise pool
      kubernetes.core.k8s:
        state: "{{ state }}"
        definition:
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: dvertise
            namespace: metallb-system