- name: control main
  hosts: control
  become: yes

  tasks:

    - name: config eth
      nmcli:
        type: ethernet
        conn_name: ethernet
        ifname: eth0
        ip4: 192.168.100.52/24
        gw4: 192.168.100.1
        state: present


    - name: deactivate wifi connection
      nmcli:
        type: wifi
        conn_name: "wlan0"
        autoconnect: false
        state: present
        ssid: "DaiKatso2"

    - name: remove default connection
      nmcli:
        type: ethernet
        conn_name: "Wired connection 1"
        state: absent

    - name: install hashicorp repo
      block:
        - name: add gpg key
          apt_key:
            url: "https://apt.releases.hashicorp.com/gpg"
            state: present
        - name: add hasicorp repo
          apt_repository:
            repo: "deb [arch=arm64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"

    - name: install packages
      apt:
        name:
          - packer
          - terraform
          - sshpass
          - vim
          - python3-pip
        update_cache: yes
        state: latest

    - name: copy ssh config for git
      copy:
        src: "ssh_git_config"
        dest: "/home/ansible/.ssh/config"
        owner: "ansible"
        group: "ansible"
