---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secrets
  namespace: tooling
spec:
  encryptedData:
    pass: AgBbkRCEPcckktjRNcNnDc+WRueabqTNAediLLooyT+l1AEvdA3piPurQ845fPJQPFd9f3x84qjHwbrDSjDUI1rFUdl07Ez5kO7sNSiLSFzsrAMwC6adCDPC++LCnTULSTCaQBdniRMLWOSbIZHyZh1Ti2ZeaspwhQ8ufQFMJr/O5RojN3/cQ1UonAnsCOgSkWO1XUnmlUB3L6cebL3wWXIeRS3DHkEn+wglEE95x/GSh8u4VIeT57PpkKa7pouvn2m+BFRIQx/tZTIlO4l73C8ru09voO+Dek5KrR9+pVE2qCm2aVFLdssl9BLvO+jJEhE0OAiE3xRszAxFe6sUWtQ79FiY/EytspwZ7QTJezjp+7i7tm9zy58RFe/huvzBfhuOCBzpTvZT/MJqMwKE3EWeFxSBmRU7HzB1rf7oZrD6XKlFjk2lC0R2m+nMOBM74ZnIP7uYhV4Ihz7uQ2wbQtSijM1QgMr2w4xIl6ft+VlQUsCFspvLPP9sBEt/NgVvt9ZThb+V4RG5aSCVm2EsXlTt8mLSLeaDshjWQEIBow+Z3zWa+I5ykq6uOFkFvLOww/5QnD0fHPKuUFxdzOFwU5sdUbezoLMR70kl1RGT4fGotCRJsT1SpasYVDtkGiiY6B0vEgZpNoOach5a1WOH7sh9c36Q28sM1ZTk4hBgq12y5ubMEKs4UTxqt7EsJNkKeVBa6gvNcee7yQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pihole
      name: pihole-secrets
      namespace: tooling
    type: Opaque
